### ISSUE TITLE
Improve formatting for help pages?

### ISSUE THREAD

**Issue by garrettgman** [rstudio/tutor#16]
Is it possible to improve how the content of help pages is formatted when a student uses an exercise to open a help page? Students will open help pages often, since these are learning documents. 

The current formatting is odd, but legible (so feel free to close the issue immediately). Two adjustments would make a big difference:

1. Disable text wrap
2. Display titles in header case (vs _t_h_i_s _c_a_s_e)

To quickly see how the help pages display, just add a `?plot` chunk to a tutorial:

    ---
    title: "Help pages display awkwardly"
    output: tutor::tutorial
    runtime: shiny_prerendered
    ---
    
    ```{r setup, include=FALSE}
    library(tutor)
    ```
    
    ```{r help, exercise = TRUE}
    ?plot
    ```

<img width="1212" alt="screen shot 2017-02-21 at 11 08 08 am" src="https://cloud.githubusercontent.com/assets/85014/23173160/3f43d258-f826-11e6-9803-fa11bae68b2c.png">

**Comment by AmeliaMN** [comment]
I think this would be great. I think I spoke to both @hadley and @jjallaire at rstudio::conf about my wish to have help in RStudio generally be more user-friendly for novices. For example, if you have ```dplyr``` loaded, ```?filter``` brings you to two topics, but that could be changed to a wikipedia-style interface where the first one in the search path displays by default and there is a "disambiguation" link at the top to access other functions with the same name.

**Comment by jjallaire** [comment]
Yes, help rendering is currently pretty terrible. I think we need to either transform the text-based help as you suggest or try to get HTML help working (that I'd much prefer).

**Comment by krlmlr** [comment]
Some of the suggested improvements are easy to achieve by calling `tools::Rd2txt_options()` in a setup chunk:

```r
tools::Rd2txt_options(underline_titles = FALSE, width = 75)
```

75 seems to be the default width in an exercise chunk.

Calling `?filter` shows the disambiguation *and* the help for `stats::filter` on my system.

**Comment by krlmlr** [comment]
Wrapping can be turned off for all output chunks by adding the following CSS:

```css
.tutorial-exercise-output pre code { white-space: pre; }
```
I achieved it by using the following YAML header

```yaml
output:
  learnr::tutorial:
    css: css/nowrap.css
```

and adding a file `nowrap.css` with the above contents in the `css` directory below the `.Rmd` document.

(Turning off the wrapping has no effect in the RStudio viewer, but works in Firefox.)

**Comment by krlmlr** [comment]
Ideally, the font size in the input and output elements would adapt to fit approximately 75 characters (or slightly more). This can be achieved by using `vw` units for the font size.

Demo: https://krlmlr.shinyapps.io/adaptive/.

Implementation: I removed the min-width for the list of topics (because it messes up the calculations) but increased its width to 30 %. I ended up with the following CSS, though I don't fully understand it:

```css
.tutorial-exercise-output pre code {
  white-space: pre;
  font-size: 1.25vw;
}

.tutorial-exercise-code-editor {
  font-size: 1.4vw;
}

.topics {
  width: 68%;
}

.topicsContainer {
  min-width: 1px;
  width: 30%;
}

.topicsList {
  min-width: 1px;
  width: 30%;
}

@media screen and (max-width: 767px) {
  .tutorial-exercise-output pre code {
    font-size: 1.85vw;
  }

  .tutorial-exercise-code-editor {
    font-size: 1.9vw;
  }

  .topics {
    width: 99%;
  }

  .topicsContainer {
    width: 1%;
  }
}
```
